### ISSUE TITLE
Will not shut off

### ISSUE THREAD

**Issue by xjazc03** [BadWolf22/AndroidJavaRock#9]
I followed your instructions and it worked great until I went to close termux, I noticed my phantom server was still showing on my PS4 and now I can't get it to turn off, please fix!

**Comment by BadWolf22** [comment]
Oh sorry, I'm a little late. You can't just close Termux, you have to shut down the Termux sessions. There should be an option in the notification to do so or you can press "Ctrl" in the Termux keyboard thing (above your actual keyboard) and then press the "c" letter on your keyboard. The "Ctrl-C" keyboard shortcut stops the focused running process in the terminal.

Let me know if you need any further help!

**Comment by xjazc03** [comment]
Thank you!
